name: Engine automated tests

on:
  push: 
    branches: [master, experimental]

jobs:
  test-linux:
    runs-on: ubuntu-latest
    name: Build and Test Engine package on linux
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v2
        with:
          version: 0.16.0
      - run: sudo apt install -y ffmpeg
      - run: zig build test
  test-macos:
    runs-on: macos-latest
    name: Build and Test Engine package on MacOS
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v2
        with:
          version: 0.16.0
      - run: brew install ffmpeg
      - run: zig build test

